### ISSUE TITLE
Improve the readme

### ISSUE THREAD

**Issue by annu12340** [annu12340/sophie-the-bot#1]
Update the readme file with:-

Better description in the readme
Installation steps

Take these repos as example
https://github.com/annu12340/virtual-white-board
https://github.com/annu12340/Choose-Smart

**Comment by love07oj** [comment]
I want to contribute in this by adding a better README.md

**Comment by annu12340** [comment]
Sure
ahead @love07oj

**Comment by annu12340** [comment]
Solved
